{% set name = "sudachipy" %}
{% set version = "0.6.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sudachipy-{{ version }}.tar.gz
  sha256: b8910a4610de98b2c3cb6dc3362fea93e3ba5059f1eb445a68baa9585278f31b

build:
  number: 0
  script: 
    - curl -O https://github.com/WorksApplications/sudachi.rs/blob/v{{ version }}/LICENSE
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - sudachipy=sudachipy.command_line:main
  missing_dso_whitelist:  # [s390x]
    - $RPATH/ld64.so.1    # [s390x]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - curl
  host:
    - pip
    - python
    - setuptools
    - wheel
    - setuptools-rust
  run:
    - python

test:
  imports:
    - sudachipy
  requires:
    - pip
  commands:
    - pip check
    - sudachipy --help

about:
  home: https://github.com/WorksApplications/sudachi.rs/tree/develop/python
  dev_url: https://github.com/WorksApplications/sudachi.rs/tree/develop/python
  doc_url: https://github.com/WorksApplications/sudachi.rs/tree/develop/python
  summary: Python version of Sudachi, the Japanese Morphological Analyzer
  description: Python version of Sudachi, the Japanese Morphological Analyzer
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  license_family: Apache

extra:
  recipe-maintainers:
    - skupr-anaconda
