{% set name = "sudachipy" %}
{% set version = "0.6.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/SudachiPy-{{ version }}.tar.gz
  sha256: e4fb026cc367e0dff7d0b8a2fce510e66d5bf7ef4728af76bfe63132b22753cd

build:
  entry_points:
    - sudachipy=sudachipy.command_line:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - setuptools
    - wheel
    - setuptools-rust
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - sudachipy
  commands:
    - pip check
    - sudachipy --help
  requires:
    - pip

about:
  home: https://github.com/WorksApplications/sudachi.rs/tree/develop/python
  summary: Python version of Sudachi, the Japanese Morphological Analyzer
  license: Apache-2.0
  license_file: PLEASE_ADD_LICENSE_FILE

extra:
  recipe-maintainers:
    - skupr-anaconda
